[package]
name = "molecular_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sdl3 = "0.14.35"
assert_approx_eq ="1.1.0"
scanf = "1.3.1"